version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: senha
      POSTGRES_USER: postgre
      POSTGRES_DB: postgre
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
